version: 2

jobs:
  build:
    context: sourceforts-server
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          docker build -t sourceforts/7zip:$CIRCLE_BUILD_NUM -t sourceforts/7zip:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/7zip:$CIRCLE_BUILD_NUM
          docker push sourceforts/7zip:latest
